apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-example
spec:
  containers:
  - name: test-container
    image: busybox
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
    command: ['sh', '-c', 'echo Hello from PVC > /test-volume/hello.txt && sleep 3600']
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: pvc-example
